export const ADD_DATA_REQUEST = "ADD_DATA_REQUEST";
export const ADD_DATA_FAILURE = "ADD_DATA_FAILURE";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const RESET_DATA_REQUEST = "RESET_DATA_REQUEST";
