export const GET_LIST_REQUEST = "GET_LIST_REQUEST";
export const GET_LIST_FAILURE = "GET_LIST_FAILURE";
export const GET_LIST_SUCCESS = "GET_LIST_SUCCESS";
export const RESET_LIST_REQUEST = "RESET_LIST_REQUEST";
